### ISSUE TITLE
Question about the evaluation code of AP

### ISSUE THREAD

**Issue by IceTTTb** [EryiXie/PlaneRecNet#3]
Thanks for your good work, but l still have some questions about the evaluation code of AP.
Specifically, in the function  `compute_segmentation_metrics` in `eval.py`:
 1. Why set `num_gt_for_class = 1` ? It will make the number of gt positives of each image always be 1.
 2. The following code also confuses me:
 
        for j in range(num_gt):
             iou = iou_func(i, j)
             ...
        if max_match_idx >= 0:
            gt_used[max_match_idx] = True
            ap_obj.push(score_func(i), True)
        ap_obj.push(score_func(i), False)
    According to  [yolact](https://github.com/dbolya/yolact/blob/master/eval.py), it seems should be:

        for j in range(num_gt):
             if gt_used[j]:
                 continue
             iou = iou_func(i, j)
             ...
        if max_match_idx >= 0:
            gt_used[max_match_idx] = True
            ap_obj.push(score_func(i), True)
        else:
            ap_obj.push(score_func(i), False)

**Comment by EryiXie** [comment]
Hi, sorry for replying to you that later. I was on vacation and now I am finally back. 

Many thanks for pointing that out. I am afraid that the issue you mention about the Average Precision is unfortunately correct. I misunderstood the num_classes and thought that since I focus only on single-class then it should = 1. For me, that's really a big issue and I will fix the code, rerun some experiments and provide the correct results of some of the metrics used in the paper. Since I use the same evaluation code to calculate the results of other works, I am pretty sure,  the conclusion will not be affected.

**Comment by IceTTTb** [comment]
> 

Thanks for your reply. I think it is still a good work and has benefited me a lot！
