### ISSUE TITLE
dataset format

### ISSUE THREAD

**Issue by RenQJ** [EryiXie/PlaneRecNet#7]
Thanks for your excellent work. I feel confused when I try to read the code about datasets.py. Can you introduce some details about scannet_*.json? How to understand the 'segmentation', 'bbox', 'area'?

**Comment by EryiXie** [comment]
I arrange the data annotation the same way as COCO data format for segmentation and detection, (https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch). Only add an extra annotation for plane parameters. 
These terms you mentioned are:
segmentation: the encoder contour of the instance mask,
bbox: the bounding box of an instance (a plane region),
area: the area of an instance (the number of pixels of a plane region).

**Comment by RenQJ** [comment]
Thank you. 
Another question is about plane parameters. As the paper said, the prn does not explicitly predict plane parameters. Why the plane parameters are added into the train dataset?

**Comment by EryiXie** [comment]
Hi, that because we still want to use the normal vector of plane regions to
supervise the depth estimation, so that the predicted depth is somehow
"flat" or at least not "rough" in these regions. The part about "plane
surface normal loss" explained the idea.

Am Fr., 25. März 2022 um 10:36 Uhr schrieb RenQJ ***@***.***>:
